### ISSUE TITLE
Wrong usage of application symbol

### ISSUE THREAD

**Issue by webdevilopers** [xuwupeng2000/capsitrano-scm-gitcopy#33]
I'm not sure if this is NOT a Capistrano issue. But since everything used to work fine in staging before implementing scm-gitcopy into production I will post it here.

In my `deploy.rb` my application symbol is set to:
```ruby
set :application, 'Semcoglas'
set :deploy_to, '/var/www/semcoweb'
```

I always regarded `application` as `App name`.

When I run `cap production deploy` everything works fine so far. All paths are used correctly based on the `deploy_to` symbol.

But then, when Composer is supposed to run, the path suddenly changes to `/var/www/Semcoglas` <- name of the `:application` symbol.

Of course I get a ***Could not open file: /var/www/Semcoglas/shared/composer.phar*** error.

I tried without defining `:application` and indeed the wrong path will become `/var/www/shared/...`.

Any idea what is happening here?

**Comment by webdevilopers** [comment]
Have you come across this issue before @leehambley? Maybe you can confirm if this issue is directly related to @capistrano? Thanks

**Comment by leehambley** [comment]
I've not seen this one before @webdevilopers - Sounds like the `capistrano-composer` Gem has a problem?

**Comment by webdevilopers** [comment]
Okay, since there is no other feedback by @xuwupeng2000 I'm gonna move this issue there. Thanks for the feedback @leehambley !
